server:
  port: 8081
security:
  oauth2:
    client:
      clientId: abc
      clientSecret: 1f320b956fe0
      accessTokenUri: https://github.com/login/oauth/access_token
      userAuthorizationUri: https://github.com/login/oauth/authorize
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
    resource:
      user-info-uri: https://api.github.com/user
